#!/usr/bin/env bash

while getopts "w" flag; do
    case "$flag" in
	w) watch=true
	   ;;
    esac
done

filename=${@:$OPTIND:1}

if ! [[ -f "$filename" ]]; then
    echo "Usage: $(basename $0) [-w] filename" >&2
    echo "  -w    Watch file and regenerate whenever it changes" >&2
    exit -1
fi

[[ -d "reveal.js" ]] || git clone -b 3.3.0 --depth 1 https://github.com/hakimel/reveal.js.git
[[ -f "Gemfile" ]] || cat << EOF >Gemfile
source 'https://rubygems.org'
gem 'asciidoctor-revealjs'
EOF
bundle config --local github.https true
bundle --path=.bundle/gems --binstubs=.bundle/.bin

compile() {
    bundle exec asciidoctor-revealjs "$1"
}

if [[ "$watch" == "" ]]; then
    compile "$filename"
else
    while inotifywait -e close_write "$filename"; do
	compile "$filename";
    done
fi
