#!/usr/bin/env bash

if ! [[ -f "$1" ]]; then
    echo "Usage: $(basename $0) <adoc_file>"
    exit -1
fi

[[ -d "reveal.js" ]] || git clone -b 3.3.0 --depth 1 https://github.com/hakimel/reveal.js.git
[[ -f "Gemfile" ]] || cat << EOF >Gemfile
source 'https://rubygems.org'
gem 'asciidoctor-revealjs'
EOF
bundle config --local github.https true
bundle --path=.bundle/gems --binstubs=.bundle/.bin
bundle exec asciidoctor-revealjs "$1"
